spring.application.name=banco

spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:3306/${DB_NAME:db_default}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}



