spring.application.name=banco

# Database Configuration
spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:3306/${DB_NAME:db_default_banco}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}


