spring.application.name=banco

spring.datasource.url=jdbc:mariadb://mariadb-crustaceo-cascarudo-bank/banco?createDatabaseIfNotExist=true
spring.datasource.username=cc-bank
spring.datasource.password=cc-bank
